version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: esgf_metrics_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file: .env
    ports:
      - "5433:5432"

  esgf_metrics:
    build:
      context: .
      dockerfile: ./docker/esgf_metrics/Dockerfile
    image: esgf_metrics
    container_name: esgf_metrics
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ${LOGS_DIR}:${LOGS_DIR}
    env_file: .env
    command: /start
